### ISSUE TITLE
demag-tool.yml does not exist

### ISSUE THREAD

**Issue by FastEddie49** [swolebro/caddyshack#1]
On Line 13, demag-tool.py references 

dims = cs.Dims("scripts/shop/magnets/demag-tool.yml")

which does not exist.  A workaround is to point the script to one of the two *.yml files in that directory.

**Comment by swolebro** [comment]
Yup, this is intentional. I haven't found any method for passing arguments to scripts in the FreeCAD CQ workbench, so when I've made multiple specs for dimensions, I've used a symlink to pick the one I wish to run. It's kind of a kludge, but it's simple, it works, and it keeps git from continually telling the script has changed just because I wanted to run a different set of specs.

There's a note about it in [this .gitignore](https://github.com/swolebro/caddyshack/blob/master/scripts/shop/.gitignore) - admittedly not the most prominent place, so I'll make a point of documenting that better.

Last I checked, the CadQuery guys were working on a branch of their library that would run outside of FreeCAD entirely. That might be worth looking into at some point, but, the ability to quickly tweak a script, re-run it, and view the output in FreeCAD is really nice.

**Comment by swolebro** [comment]
Added a blurb in the README about this, and added an extra check so that missing YAML files raise a FileNotFoundError instead being misinterpreted as a string of YAML (later leading to a KeyError).

Gonna call that good enough, for now at least.
